server:
  port: 8100
spring:
  application:
    name: eureka-service
eureka:
  client:
# 本身该引用就是注册中心，不需要向注册中心注册自己
    register-with-eureka: false
  # 注册中心只需要维护服务实例
    fetch-registry: false
    service-url:
  # eureka客户端的服务注册地址
      defaultZone: http://127.0.0.1:${server.port}/eureka/