# redis配置
spring:
  redis:
    # redis数据库索引
    database: 0
    # redis服务器地址
    host: 127.0.0.1
    # redis端口号
    port: 6379
    # redis密码
    # password:

    # redis连接池配置
    jedis:
      pool:
        # 连接池最大的连接数 (使用负值时表示没有任何的限制)
        max-active: 200
        # 连接池最大阻塞等待时间 (使用负值时表示没有任何的限制)
        max-wait: -1
        # 连接池中最大空闲连接数
        max-idle: 10
        # 连接池最小的空闲连接
        min-idle: 0
    # 连接超时(单位是ms)
    timeout: 1000